// <auto-generated />
using System;
using LoguiSueldo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoguiSueldo.Migrations
{
    [DbContext(typeof(LoguiSueldoContext))]
    [Migration("20250825120816_inicial2")]
    partial class inicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoguiSueldo.Models.ART", b =>
                {
                    b.Property<int>("ArtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtID"));

                    b.Property<int>("ConvenioID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtID");

                    b.ToTable("ARTs");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Administracion.ClientesLogui", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<string>("NroTipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoContribuyenteID")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteID");

                    b.ToTable("ClientesLogui");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Antiguedad_Convenio", b =>
                {
                    b.Property<int>("AntiguedadConvenioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntiguedadConvenioID"));

                    b.Property<bool>("CalculaPorAnio")
                        .HasColumnType("bit");

                    b.Property<int>("ConvenioID")
                        .HasColumnType("int");

                    b.Property<decimal>("Desde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hasta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AntiguedadConvenioID");

                    b.ToTable("AntiguedadConvenios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<decimal>("CantUnidades")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sueldo_basico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoUnidad")
                        .HasColumnType("int");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Concepto_Afip", b =>
                {
                    b.Property<string>("ConceptoAfip")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AporteFondo")
                        .HasColumnType("bit");

                    b.Property<bool>("AporteObraSocial")
                        .HasColumnType("bit");

                    b.Property<bool>("AporteRegDiferencial")
                        .HasColumnType("bit");

                    b.Property<bool>("AporteRegEspeciales")
                        .HasColumnType("bit");

                    b.Property<bool>("AporteRenatae")
                        .HasColumnType("bit");

                    b.Property<bool>("AportesInssjyp")
                        .HasColumnType("bit");

                    b.Property<bool>("AportesSipa")
                        .HasColumnType("bit");

                    b.Property<int>("ConceptoID")
                        .HasColumnType("int");

                    b.Property<bool>("ContribucionAsigFamiliar")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionFondo")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionFondoEmpleo")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionInssjyp")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionObraSocial")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionRenatae")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionRiesgoTrabajo")
                        .HasColumnType("bit");

                    b.Property<bool>("ContribucionSipa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Repeticion")
                        .HasColumnType("bit");

                    b.Property<bool>("Seleccion")
                        .HasColumnType("bit");

                    b.HasKey("ConceptoAfip");

                    b.ToTable("ConceptosAfip");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Conceptos", b =>
                {
                    b.Property<int>("ConceptoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConceptoID"));

                    b.Property<int>("Asiento")
                        .HasColumnType("int");

                    b.Property<int>("Bloque")
                        .HasColumnType("int");

                    b.Property<int>("ConvenioID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inamobible")
                        .HasColumnType("bit");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreVariable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Remunerable")
                        .HasColumnType("bit");

                    b.Property<bool>("sel")
                        .HasColumnType("bit");

                    b.HasKey("ConceptoID");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Convenio", b =>
                {
                    b.Property<int>("ConvenioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConvenioID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConvenioID");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Empleado", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaID"));

                    b.Property<int>("AnioAntiguedad")
                        .HasColumnType("int");

                    b.Property<int>("ArtID")
                        .HasColumnType("int");

                    b.Property<float>("Basico")
                        .HasColumnType("real");

                    b.Property<float>("CantidadHoras")
                        .HasColumnType("real");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<int>("Cct")
                        .HasColumnType("int");

                    b.Property<int>("CodigoActividad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCondicion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoContratacion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestrado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSituacion")
                        .HasColumnType("int");

                    b.Property<int>("ConvenioID")
                        .HasColumnType("int");

                    b.Property<int>("Conyugue")
                        .HasColumnType("int");

                    b.Property<int>("Cuil")
                        .HasColumnType("int");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<float>("Extra1")
                        .HasColumnType("real");

                    b.Property<float>("Extra2")
                        .HasColumnType("real");

                    b.Property<float>("Extra3")
                        .HasColumnType("real");

                    b.Property<float>("Extra4")
                        .HasColumnType("real");

                    b.Property<float>("Extra5")
                        .HasColumnType("real");

                    b.Property<float>("Extra6")
                        .HasColumnType("real");

                    b.Property<DateTime>("FechaAltaRecibo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Hijos")
                        .HasColumnType("int");

                    b.Property<float>("HorasEnfAcc")
                        .HasColumnType("real");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadID")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadLiquidacion")
                        .HasColumnType("int");

                    b.Property<float>("MontoHoraExtra")
                        .HasColumnType("real");

                    b.Property<float>("MontoHorasFeriado")
                        .HasColumnType("real");

                    b.Property<float>("MontoHorasFeriado_tjdo")
                        .HasColumnType("real");

                    b.Property<float>("MontoUltimoRecibo")
                        .HasColumnType("real");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraSocialID")
                        .HasColumnType("int");

                    b.Property<float>("PorcentajeAntiguedad")
                        .HasColumnType("real");

                    b.Property<float>("PorcentajeJubilacion")
                        .HasColumnType("real");

                    b.Property<float>("PorcentajeObraSocial")
                        .HasColumnType("real");

                    b.Property<float>("PrecioHoras")
                        .HasColumnType("real");

                    b.Property<int>("Reduccion")
                        .HasColumnType("int");

                    b.Property<int>("SistJubilID")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UltimoPeriodoLiquidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Empleado_Adicional", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaID"));

                    b.Property<float>("AporteAdicionalObraSocial")
                        .HasColumnType("real");

                    b.Property<float>("AporteAdicional_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseDiferencialAporte_os_fsr")
                        .HasColumnType("real");

                    b.Property<float>("BaseDiferencialContribucion_os_fsr")
                        .HasColumnType("real");

                    b.Property<float>("BaseDiferencial_lrt")
                        .HasColumnType("real");

                    b.Property<int>("CodigoSiniestro1")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestro2")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestro3")
                        .HasColumnType("int");

                    b.Property<float>("ContribucionAdicional")
                        .HasColumnType("real");

                    b.Property<float>("ContribucionAdicionalObraSocial")
                        .HasColumnType("real");

                    b.Property<int>("DiaSiniestro1")
                        .HasColumnType("int");

                    b.Property<int>("DiaSiniestro2")
                        .HasColumnType("int");

                    b.Property<int>("DiaSiniestro3")
                        .HasColumnType("int");

                    b.Property<float>("MaternidadAnses")
                        .HasColumnType("real");

                    b.Property<bool>("MediaJornada")
                        .HasColumnType("bit");

                    b.Property<int>("TipoEmpleador")
                        .HasColumnType("int");

                    b.HasKey("PersonaID");

                    b.ToTable("Empleados_Adicional");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaID"));

                    b.Property<bool>("AgenteRetencionGanancias")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cargado")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cuit")
                        .HasColumnType("int");

                    b.Property<string>("DireccionReal")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int");

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroTipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("LoguiSueldo.Models.EmpresaOnline", b =>
                {
                    b.Property<int>("EmpresaOnlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaOnlineID"));

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimoIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioOnline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaOnlineID");

                    b.ToTable("EmpresasOnline");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Horas_empleados", b =>
                {
                    b.Property<int>("EmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoID"));

                    b.Property<float>("HorasAccCant")
                        .HasColumnType("real");

                    b.Property<float>("HorasEnfermoCant")
                        .HasColumnType("real");

                    b.Property<float>("HorasExtrasCant")
                        .HasColumnType("real");

                    b.Property<float>("HorasFeriadoCant")
                        .HasColumnType("real");

                    b.Property<float>("HorasFeriadoTrabajado")
                        .HasColumnType("real");

                    b.Property<float>("HorasNormalesCant")
                        .HasColumnType("real");

                    b.Property<float>("Km_Cantidad")
                        .HasColumnType("real");

                    b.Property<float>("Km_Cantidad_item424")
                        .HasColumnType("real");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<float>("anio")
                        .HasColumnType("real");

                    b.HasKey("EmpleadoID");

                    b.ToTable("Horas_Empleados");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Leyes", b =>
                {
                    b.Property<int>("LeyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeyID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeyID");

                    b.ToTable("Leyes");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Libro_sueldo", b =>
                {
                    b.Property<int>("LibroSueldoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroSueldoID"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_reg_4")
                        .HasColumnType("int");

                    b.Property<float>("CuitEmpleador")
                        .HasColumnType("real");

                    b.Property<int>("DiasBase")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ley")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLiquidacion")
                        .HasColumnType("int");

                    b.Property<float>("Periodo")
                        .HasColumnType("real");

                    b.Property<string>("TipoLiquidador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroSueldoID");

                    b.ToTable("LibroSueldos");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Libro_sueldo_adicional", b =>
                {
                    b.Property<int>("LibroSueldoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroSueldoID"));

                    b.Property<float>("AporteAdicional_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseDifAporte_os_fsr")
                        .HasColumnType("real");

                    b.Property<float>("BaseDifAportes_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseDifCont_os_fsr")
                        .HasColumnType("real");

                    b.Property<float>("BaseDifContribucion_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseDif_lrt")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible1")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible10")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible2")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible3")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible4")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible5")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible6")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible7")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible8")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible9")
                        .HasColumnType("real");

                    b.Property<int>("CantidadAdherentes")
                        .HasColumnType("int");

                    b.Property<int>("Cct")
                        .HasColumnType("int");

                    b.Property<int>("CodActividad")
                        .HasColumnType("int");

                    b.Property<int>("CodCondicion")
                        .HasColumnType("int");

                    b.Property<int>("CodContratacion")
                        .HasColumnType("int");

                    b.Property<int>("CodLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("CodSiniestrado")
                        .HasColumnType("int");

                    b.Property<int>("CodSituacion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoObraSocial")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestro1")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestro2")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSiniestro3")
                        .HasColumnType("int");

                    b.Property<float>("ContribucionAdicional")
                        .HasColumnType("real");

                    b.Property<int>("Conyugue")
                        .HasColumnType("int");

                    b.Property<int>("Cuil")
                        .HasColumnType("int");

                    b.Property<int>("DiaSiniestro1")
                        .HasColumnType("int");

                    b.Property<int>("DiaSiniestro2")
                        .HasColumnType("int");

                    b.Property<int>("DiaSiniestro3")
                        .HasColumnType("int");

                    b.Property<int>("DiasTrabajados")
                        .HasColumnType("int");

                    b.Property<int>("Hijos")
                        .HasColumnType("int");

                    b.Property<float>("HorasTrabajadas")
                        .HasColumnType("real");

                    b.Property<float>("ImporteDetraer")
                        .HasColumnType("real");

                    b.Property<float>("MaternidadAnses")
                        .HasColumnType("real");

                    b.Property<int>("PersonaID")
                        .HasColumnType("int");

                    b.Property<int>("ReciboID")
                        .HasColumnType("int");

                    b.Property<int>("Reduccion")
                        .HasColumnType("int");

                    b.Property<float>("RemuneracionBruto")
                        .HasColumnType("real");

                    b.Property<int>("Svco")
                        .HasColumnType("int");

                    b.Property<int>("TipoEmpresa")
                        .HasColumnType("int");

                    b.HasKey("LibroSueldoID");

                    b.ToTable("LibroSueldoAdicionales");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Localidad", b =>
                {
                    b.Property<int>("LocalidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalidadID"));

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.HasKey("LocalidadID");

                    b.HasIndex("ProvinciaID");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Modalidad", b =>
                {
                    b.Property<int>("ModalidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModalidadID"));

                    b.Property<float>("Codigo_afip")
                        .HasColumnType("real");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModalidadID");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Obra_social", b =>
                {
                    b.Property<int>("ObraSocialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraSocialID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraSocialID");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Pais", b =>
                {
                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.Property<string>("NoDenominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("PaisID");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoID"));

                    b.Property<string>("PermisoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermisoID");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("LoguiSueldo.Models.PermisoUsuario", b =>
                {
                    b.Property<int>("PermisoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoUsuarioID"));

                    b.Property<string>("CodigoSeguridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Desvinculado")
                        .HasColumnType("bit");

                    b.Property<int>("Digitos")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("PermisoID")
                        .HasColumnType("int");

                    b.Property<int>("PersonaID")
                        .HasColumnType("int");

                    b.Property<int>("SolicitarCodigo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermisoUsuarioID");

                    b.HasIndex("EmpresaID");

                    b.HasIndex("PermisoID");

                    b.ToTable("PermisoUsuarios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Persona", b =>
                {
                    b.Property<int>("PersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaID"));

                    b.Property<int>("CodPostal")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionReal")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NroTipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.Property<string>("Telefono1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoID")
                        .HasColumnType("int");

                    b.HasKey("PersonaID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Plantilla", b =>
                {
                    b.Property<int>("PlantillaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaID"));

                    b.Property<int>("ConvenioID")
                        .HasColumnType("int");

                    b.Property<float>("Descripcion")
                        .HasColumnType("real");

                    b.HasKey("PlantillaID");

                    b.ToTable("Plantillas");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Plantilla_Detalle", b =>
                {
                    b.Property<int>("PlantillaDetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaDetalleID"));

                    b.Property<bool>("CalcularUnidad")
                        .HasColumnType("bit");

                    b.Property<int>("ConceptoID")
                        .HasColumnType("int");

                    b.Property<int>("Inputacion")
                        .HasColumnType("int");

                    b.Property<int>("PlantillaID")
                        .HasColumnType("int");

                    b.Property<int>("TipoUnidad")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadSubfijo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantillaDetalleID");

                    b.ToTable("PlantillaDetalles");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Plantilla_empleado", b =>
                {
                    b.Property<int>("PlantillaEmpleadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantillaEmpleadoID"));

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantillaID")
                        .HasColumnType("int");

                    b.HasKey("PlantillaEmpleadoID");

                    b.ToTable("PlantillaEmpleados");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Provincia", b =>
                {
                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.Property<int>("PaisID")
                        .HasColumnType("int");

                    b.Property<string>("ProvinciaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinciaID");

                    b.HasIndex("PaisID");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Recibo", b =>
                {
                    b.Property<int>("ReciboID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReciboID"));

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cbu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DiasLiquidado")
                        .HasColumnType("real");

                    b.Property<string>("EmpleadoCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoCuit")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmpleadoFechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeposito")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPago")
                        .HasColumnType("int");

                    b.Property<string>("LugarPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MontoLetras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePeriodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoAño")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("int");

                    b.Property<int>("PlantillaID")
                        .HasColumnType("int");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("TipoReciboDetalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalBolsillo")
                        .HasColumnType("real");

                    b.Property<float>("TotalDescuento")
                        .HasColumnType("real");

                    b.Property<float>("TotalExtras")
                        .HasColumnType("real");

                    b.Property<float>("TotalRemunerativo")
                        .HasColumnType("real");

                    b.Property<float>("TotalRemunerativoSinExtra")
                        .HasColumnType("real");

                    b.HasKey("ReciboID");

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Recibo_Sueldo_DatosAdicionales", b =>
                {
                    b.Property<int>("ReciboID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReciboID"));

                    b.Property<float>("BaseDifAportes_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseDifContribucion_ss")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible1")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible10")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible2")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible3")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible4")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible5")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible6")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible7")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible8")
                        .HasColumnType("real");

                    b.Property<float>("BaseImponible9")
                        .HasColumnType("real");

                    b.Property<int>("EmpleadoID")
                        .HasColumnType("int");

                    b.Property<float>("ImporteDetraer")
                        .HasColumnType("real");

                    b.Property<int>("PeriodoAño")
                        .HasColumnType("int");

                    b.Property<int>("PeriodoMes")
                        .HasColumnType("int");

                    b.Property<float>("RemuneracionBruta")
                        .HasColumnType("real");

                    b.HasKey("ReciboID");

                    b.ToTable("Recibo_Sueldos");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Sist_jubil", b =>
                {
                    b.Property<int>("SistJubilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SistJubilID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SistJubilID");

                    b.ToTable("SistJubilatorios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Empresa", b =>
                {
                    b.HasOne("LoguiSueldo.Models.Localidad", "Localidades")
                        .WithMany("Empresa")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Localidad", b =>
                {
                    b.HasOne("LoguiSueldo.Models.Provincia", "Provincias")
                        .WithMany("Localidad")
                        .HasForeignKey("ProvinciaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("LoguiSueldo.Models.PermisoUsuario", b =>
                {
                    b.HasOne("LoguiSueldo.Models.Empresa", "Empresa")
                        .WithMany("PermisoUsuarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoguiSueldo.Models.Permiso", "Permiso")
                        .WithMany("PermisoUsuarios")
                        .HasForeignKey("PermisoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Persona", b =>
                {
                    b.HasOne("LoguiSueldo.Models.Localidad", "Localidades")
                        .WithMany("Persona")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Provincia", b =>
                {
                    b.HasOne("LoguiSueldo.Models.Pais", "Paises")
                        .WithMany("Provincia")
                        .HasForeignKey("PaisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paises");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Empresa", b =>
                {
                    b.Navigation("PermisoUsuarios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Localidad", b =>
                {
                    b.Navigation("Empresa");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Pais", b =>
                {
                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Permiso", b =>
                {
                    b.Navigation("PermisoUsuarios");
                });

            modelBuilder.Entity("LoguiSueldo.Models.Provincia", b =>
                {
                    b.Navigation("Localidad");
                });
#pragma warning restore 612, 618
        }
    }
}
